FROM fedora

COPY requirements.txt requirements-dev.txt /

RUN dnf install -y\
 wget\
 python2-pip\
 npm\
&& dnf groupinstall -y "Development Tools" \
&& pip3 install ipdb ipython \
&& pip3 install -r /requirements.txt \
&& pip3 install -r /requirements-dev.txt \
&& rm -f /requirements.txt /requirements-dev.txt
